"""create cases and case_chunks tables

Revision ID: 11ec5528bd44
Revises: 78f19e844fc3
Create Date: 2026-07-27 19:48:53.211545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ec5528bd44'
down_revision: Union[str, Sequence[str], None] = 'cee040fef122'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():

    op.create_table(
        "cases",

        sa.Column(
            "id",
            sa.Integer(),
            nullable=False
        ),

        sa.Column(
            "title",
            sa.String(length=500),
            nullable=False
        ),

        sa.Column(
            "case_number",
            sa.String(length=100),
            nullable=False
        ),

        sa.Column(
            "year",
            sa.Integer(),
            nullable=True
        ),

        sa.Column(
            "month",
            sa.Integer(),
            nullable=True
        ),

        sa.Column(
            "decision_date",
            sa.Date(),
            nullable=True
        ),

        sa.Column(
            "division",
            sa.String(length=100),
            nullable=True
        ),

        sa.Column(
            "ponencia",
            sa.String(length=255),
            nullable=True
        ),

        sa.Column(
            "pdf_path",
            sa.String(length=500),
            nullable=False
        ),

        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True
        ),

        sa.PrimaryKeyConstraint("id")
    )

    op.create_table(
    "case_chunks",

    sa.Column(
        "id",
        sa.Integer(),
        nullable=False
    ),

    sa.Column(
        "case_id",
        sa.Integer(),
        nullable=False
    ),

    sa.Column(
        "chunk_number",
        sa.Integer(),
        nullable=False
    ),

    sa.Column(
        "chunk_text",
        sa.Text(),
        nullable=False
    ),

    sa.Column(
        "chroma_document_id",
        sa.String(length=255),
        nullable=False
    ),

    sa.Column(
        "created_at",
        sa.DateTime(),
        nullable=True
    ),

    sa.ForeignKeyConstraint(
        ["case_id"],
        ["cases.id"]
    ),

    sa.PrimaryKeyConstraint("id")
)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
